### ISSUE TITLE
POS issue after install

### ISSUE THREAD

**Issue by Labyrinth-00** [aisenyi/pasigono#2]
Hi 

My setup is 
erpnext 13.21.0
frappe 13.21.0
pasigono 0.0.1
posawesome 3.2.1

How do I full remove this app?

I tried this command but I have two issues 

bench --site sitename uninstall-app pasigono --force

![image](https://user-images.githubusercontent.com/62351641/156909907-0fd764ae-31a2-47db-ba54-8bf7fee83158.png)

![image](https://user-images.githubusercontent.com/62351641/156909922-cbd36c15-a005-4319-9a21-e80ce3061f84.png)

**Comment by aisenyi** [comment]
Hello @Labyrinth-00 the process of removing the app is the same as for any other Frappe app. After running the uninstall command also run bench remove-app pasigono and then run bench build command to rebuild the assets. You can view a list of bench commands here https://frappeframework.com/docs/v13/user/en/bench/resources/bench-commands-cheatsheet

**Comment by Labyrinth-00** [comment]
Hi, thanks. 
   
   
    
   
  
    I ran these commands bench update --build, bench restart 
   
  
    but these options still remain. 
   
   
    
    
   
   
   
     On 03/07/2022 7:36 AM Aisenyi Malisa ***@***.***> wrote: 
    
    
     
    
    
     
    
    
   Hello @Labyrinth-00 the process of removing the app is the same as for any other Frappe app. After running the uninstall command also run bench remove-app pasigono and then run bench build command to rebuild the assets. You can view a list of bench commands here https://frappeframework.com/docs/v13/user/en/bench/resources/bench-commands-cheatsheet

**Comment by aisenyi** [comment]
Did you run bench remove-app pasigono
